seed: 42
model:
  root: /kaggle/input/models/phngdiuthanhngn/personalplex-7b-v1/pytorch/default/1 # Path đến model personaplex-7b
  source: ../src # Path đến thư mục chứa code của PersonaPlex
  device: cuda
data:
  prepared_dir: /kaggle/input/datasets/ngocbaotrinhtuan/personaplex-otospeech-prepared/prepared # Contains train.jsonl and samples/conv_XXXX
  window_seconds: 5 # Minimal window (5 seconds) for safe GPU memory smoke test
  shuffle: false # Shuffle 
lora:
  rank: 2
  alpha: 4
  qlora: false
  quant_type: nf4
train:
  output_dir: ../runs/hf_overfit_10
  max_steps: 300
  learning_rate: 2.0e-5
