# Hydra configuration for training on a subset of samples (>1 sample).
defaults:
  - model: server
  - data: vietnamese
  - lora: default
  - _self_

seed: 42
duration_sec: 100
sample_number: 10             # Number of unique conversations to train on (> 1)
sample_index: null
profile_steps: false
free_running_eval_every_steps: 0
free_running_eval_samples: 3
free_running_eval_window_seconds: 30
validation_max_samples: 32
batch_size: 1                 # Per GPU
max_steps: 2000

data:
  shuffle: true

lora:
  enable: true
  rank: 128
  scaling: 2.0
  ft_embed: false

# Dual Learning Rates
optim:
  lr: 2.0e-5                   # Temporal Transformer (7B) learning rate
  weight_decay: 0.1
  pct_start: 0.05

train:
  output_dir: ../runs/personaplex-some-samples
  learning_rate: 2.0e-5             # Temporal Transformer (7B) learning rate
  depformer_learning_rate: 5.0e-5   # Depth Transformer (0.1B) learning rate
  stage: joint
  gradient_accumulation_steps: 4
  eval_every_steps: 0
  mixed_precision: bf16
  num_workers: 4
  filter_num_workers: 64
  prefetch_factor: 2
  pin_memory: true
  persistent_workers: true

first_codebook_weight_multiplier: 1.0
text_padding_weight: 0.3
log_freq: 1
no_eval: true
ckpt_freq: 100
gradient_checkpointing: true

generation:
  use_sampling: true
  temp: 0.7
  temp_text: 0.6
  top_k: 250
  top_k_text: 25
  audio_silence_frame_cnt: 6
